application:
  env: PROD

inventory:
  db-host: prodHost

spring:
  datasource:
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: rabbitHost
    port: 5671
    username: ${RABBIT_MQ_USR}
    password: ${RABBIT_MQ_PWD}
    ssl:
      enabled: true


management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: health,refresh
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: always
      enabled: true
    refresh:
      enabled: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
